name: CI/CD Mini Pipeline LLM

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Installazione delle dipendenze
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow psycopg2 pandas langchain_community

      # Configurazione del server MLflow
      - name: Set MLflow tracking URI
        run: echo "MLFLOW_TRACKING_URI=http://host.docker.internal:5000" >> $GITHUB_ENV

      # Esecuzione dello script Python
      - name: Run Python script
        run: python /workspace/rag_pdf.py
        env:
          MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
