jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gpt4all numpy psycopg2 matplotlib seaborn mlflow pandas sentence-transformers pypdf langchain_community faiss-cpu

      # Run Python script
      - name: Run Python script
        run: python /mnt/c/Users/mnico/Documents/esempietto/rag_pdf.py
        env:
          MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}

      - name: Build Docker image with MLflow
        run: |
          mlflow models build-docker \
            --model-uri models:/GPT4All_Orca_Model/latest \
            --name llmdocker \
            --env-manager=local
        env:
          MLFLOW_TRACKING_URI: http://host.docker.internal:5000

