jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow psycopg2 pandas langchain_community

      # Configure MLflow tracking URI
      - name: Set MLflow tracking URI
        run: echo "MLFLOW_TRACKING_URI=http://host.docker.internal:5000" >> $GITHUB_ENV

      # Run Python script
      - name: Run Python script
        run: python /c/Users/mnico/Documents/esempietto/rag_pdf.py
        env:
          MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
